// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vertr.Orders.Infrastructure.DataAccess;

#nullable disable

namespace Vertr.Orders.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(OrdersContext))]
    partial class OrdersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vertr.Orders.Domain.OrderRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class_code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument_id");

                    b.Property<long>("Lots")
                        .HasColumnType("bigint")
                        .HasColumnName("lots");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.HasKey("Id")
                        .HasName("pk_order_requests");

                    b.ToTable("order_requests", (string)null);
                });

            modelBuilder.Entity("Vertr.Orders.Domain.OrderResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommissionCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commission_currency");

                    b.Property<decimal>("CommissionValue")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_value");

                    b.Property<long>("LotsExecuted")
                        .HasColumnType("bigint")
                        .HasColumnName("lots_executed");

                    b.Property<long>("LotsRequested")
                        .HasColumnType("bigint")
                        .HasColumnName("lots_requested");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("OrderRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_request_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_order_responses");

                    b.ToTable("order_responses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
